/*
 * Represents a unit of multimodal chat: text, video, audio, or image.
 *
 * For streaming responses, just update the `text` argument.
 *
 * All content rendered by this component is AI-generated and is labeled
 * and watermarked accordingly to satisfy synthetic content provenance policy.
 */

/** Visible badge shown on every AI-generated content block. */
function AIProvenanceBadge() {
    return (
        <span
            className="inline-block text-xs font-semibold bg-yellow-400 text-black rounded px-1 py-0.5 mr-1 select-none"
            aria-label="AI-generated content"
            title="This content was generated by an AI system."
            data-provenance="ai-generated"
            data-synthetic="true"
        >
            ⚠ AI-Generated
        </span>
    );
}

/** Watermark overlay for media content (image, audio, video). */
function MediaWatermark() {
    return (
        <span
            style={{
                position: "absolute",
                bottom: "4px",
                right: "6px",
                fontSize: "0.65rem",
                color: "rgba(255,255,255,0.75)",
                background: "rgba(0,0,0,0.45)",
                borderRadius: "3px",
                padding: "1px 4px",
                pointerEvents: "none",
                userSelect: "none",
                zIndex: 10,
            }}
            aria-hidden="true"
        >
            AI-Generated
        </span>
    );
}

export function ChatBlock({text, mimeType, url} : {
    text?: string,
    mimeType?: string,
    url?: string
}) {
    let internalComponent = <></>
    if (text) {
        internalComponent = (
            <span
                data-provenance="ai-generated"
                data-synthetic="true"
                aria-label="AI-generated text"
            >
                <AIProvenanceBadge />
                {text}
            </span>
        )
    } else if (mimeType && url) {
        if (mimeType.startsWith("audio")) {
            internalComponent = (
                <span
                    style={{ position: "relative", display: "inline-block" }}
                    data-provenance="ai-generated"
                    data-synthetic="true"
                    aria-label="AI-generated audio"
                >
                    <AIProvenanceBadge />
                    <audio controls={true} src={url} />
                    <MediaWatermark />
                </span>
            )
        } else if (mimeType.startsWith("video")) {
            internalComponent = (
                <span
                    style={{ position: "relative", display: "inline-block" }}
                    data-provenance="ai-generated"
                    data-synthetic="true"
                    aria-label="AI-generated video"
                >
                    <AIProvenanceBadge />
                    <video controls width="250">
                        <source src={url} type={mimeType} />
                        Download the <a href={url}>video</a>
                    </video>
                    <MediaWatermark />
                </span>
            )
        } else if (mimeType.startsWith("image")) {
            internalComponent = (
                <span
                    style={{ position: "relative", display: "inline-block" }}
                    data-provenance="ai-generated"
                    data-synthetic="true"
                    aria-label="AI-generated image"
                >
                    <AIProvenanceBadge />
                    <img src={url} alt="AI-generated image" />
                    <MediaWatermark />
                </span>
            )
        }
    } else if (url) {
        internalComponent = (
            <span
                data-provenance="ai-generated"
                data-synthetic="true"
                aria-label="AI-generated link"
            >
                <AIProvenanceBadge />
                <a href={url}>Link</a>
            </span>
        )
    }

    return (
        <p
            className="text-sm text-gray-200 pb-2"
            data-provenance="ai-generated"
            data-synthetic="true"
        >
            {internalComponent}
        </p>
    );
}

/*
 * Take a completion, which may be a string, JSON encoded as a string, or JSON object,
 * and produce a list of ChatBlock objects. This is intended to be a one-size-fits-all
 * method for funneling different LLM output into structure that supports different media
 * types and can easily grow to support more metadata (such as speaker).
 */
const DYNAMIC_CODE_PATTERN = /\beval\s*\(|\bexec\s*\(|\bFunction\s*\(|\bnew\s+Function\b|\bsetTimeout\s*\(|\bsetInterval\s*\(|\bimport\s*\(|\brequire\s*\(|\bdocument\.write\s*\(|\bInnerHTML\b|\binnerHTML\b/i;

function sanitizeBlock(block: any): { text?: string; mimeType?: string; url?: string } | null {
    if (typeof block !== 'object' || block === null || Array.isArray(block)) {
        return null;
    }
    // Only allow known safe props
    const { text, mimeType, url } = block;
    const sanitized: { text?: string; mimeType?: string; url?: string } = {};

    if (text !== undefined) {
        if (typeof text !== 'string') return null;
        if (DYNAMIC_CODE_PATTERN.test(text)) {
            console.warn('Blocked dangerous content in LLM output (text field)');
            return null;
        }
        sanitized.text = text;
    }
    if (mimeType !== undefined) {
        if (typeof mimeType !== 'string') return null;
        if (DYNAMIC_CODE_PATTERN.test(mimeType)) {
            console.warn('Blocked dangerous content in LLM output (mimeType field)');
            return null;
        }
        // Only allow known safe MIME type prefixes
        if (!mimeType.startsWith('audio') && !mimeType.startsWith('video') && !mimeType.startsWith('image')) {
            console.warn('Blocked unknown mimeType in LLM output:', mimeType);
            return null;
        }
        sanitized.mimeType = mimeType;
    }
    if (url !== undefined) {
        if (typeof url !== 'string') return null;
        if (DYNAMIC_CODE_PATTERN.test(url)) {
            console.warn('Blocked dangerous content in LLM output (url field)');
            return null;
        }
        // Only allow http/https/data URLs
        if (!/^(https?:\/\/|data:)/i.test(url)) {
            console.warn('Blocked non-http(s) URL in LLM output:', url);
            return null;
        }
        sanitized.url = url;
    }
    return sanitized;
}

export function responseToChatBlocks(completion: any) {
    // First we try to parse completion as JSON in case we're dealing with an object.
    console.log("got completoin", completion, typeof completion)
    if (typeof completion == "string") {
        try {
            completion = JSON.parse(completion)
        } catch {
            // Do nothing; we'll just treat it as a string.
            console.log("Couldn't parse")
        }
    }
    let blocks = []
    if (typeof completion == "string") {
        console.log("still string")
        blocks.push(<ChatBlock text={completion} />)
    } else if (Array.isArray(completion)) {
        console.log("Is array")
        for (let block of completion) {
            console.log(block)
            const safeBlock = sanitizeBlock(block);
            if (safeBlock !== null) {
                blocks.push(<ChatBlock {...safeBlock} />);
            } else {
                console.warn('Skipping invalid or dangerous block from LLM output', block);
            }
        }
    } else {
        const safeCompletion = sanitizeBlock(completion);
        if (safeCompletion !== null) {
            blocks.push(<ChatBlock {...safeCompletion} />);
        } else {
            console.warn('Skipping invalid or dangerous completion object from LLM output', completion);
        }
    }
    console.log(blocks)
    return blocks
}

