/*
 * Represents a unit of multimodal chat: text, video, audio, or image.
 *
 * For streaming responses, just update the `text` argument.
 *
 * All content rendered by this component is AI-generated and is labeled
 * and watermarked accordingly to satisfy synthetic content provenance policy.
 */

/** Visible badge shown on every AI-generated content block. */
function AIProvenanceBadge() {
    return (
        <span
            className="inline-block text-xs font-semibold bg-yellow-400 text-black rounded px-1 py-0.5 mr-1 select-none"
            aria-label="AI-generated content"
            title="This content was generated by an AI system."
            data-provenance="ai-generated"
            data-synthetic="true"
        >
            ⚠ AI-Generated
        </span>
    );
}

/** Watermark overlay for media content (image, audio, video). */
function MediaWatermark() {
    return (
        <span
            style={{
                position: "absolute",
                bottom: "4px",
                right: "6px",
                fontSize: "0.65rem",
                color: "rgba(255,255,255,0.75)",
                background: "rgba(0,0,0,0.45)",
                borderRadius: "3px",
                padding: "1px 4px",
                pointerEvents: "none",
                userSelect: "none",
                zIndex: 10,
            }}
            aria-hidden="true"
        >
            AI-Generated
        </span>
    );
}

function sanitizeMimeType(mime: string | undefined): string {
    if (!mime) return '';
    // Only allow safe 'type/subtype' format, strip parameters and special chars
    const match = mime.match(/^([a-zA-Z0-9][a-zA-Z0-9!#$&\-^_]*\/[a-zA-Z0-9][a-zA-Z0-9!#$&\-^_.+]*)/);
    return match ? match[1] : '';
}

function sanitizeUrl(url: string | undefined): string {
    if (!url) return '';
    try {
        const parsed = new URL(url);
        if (!['http:', 'https:'].includes(parsed.protocol)) return '';
        return url;
    } catch {
        return '';
    }
}

export function ChatBlock({text, mimeType, url} : {
    text?: string,
    mimeType?: string,
    url?: string
}) {
    const safeUrl = sanitizeUrl(url);
    const safeMimeType = sanitizeMimeType(mimeType);
    let internalComponent = <></>
    if (text) {
        internalComponent = (
            <span
                data-provenance="ai-generated"
                data-synthetic="true"
                aria-label="AI-generated text"
            >
                <AIProvenanceBadge />
                {text}
            </span>
        )
    } else if (mimeType && url) {
        if (safeMimeType.startsWith("audio") && safeUrl) {
            internalComponent = (
                <span
                    style={{ position: "relative", display: "inline-block" }}
                    data-provenance="ai-generated"
                    data-synthetic="true"
                    aria-label="AI-generated audio"
                >
                    <AIProvenanceBadge />
                    <audio controls={true} src={safeUrl} />
                    <MediaWatermark />
                </span>
            )
        } else if (safeMimeType.startsWith("video") && safeUrl) {
            internalComponent = (
                <span
                    style={{ position: "relative", display: "inline-block" }}
                    data-provenance="ai-generated"
                    data-synthetic="true"
                    aria-label="AI-generated video"
                >
                    <AIProvenanceBadge />
                    <video controls width="250">
                        <source src={safeUrl} type={safeMimeType} />
                        Download the <a href={safeUrl}>video</a>
                    </video>
                    <MediaWatermark />
                </span>
            )
        } else if (safeMimeType.startsWith("image") && safeUrl) {
            internalComponent = (
                <span
                    style={{ position: "relative", display: "inline-block" }}
                    data-provenance="ai-generated"
                    data-synthetic="true"
                    aria-label="AI-generated image"
                >
                    <AIProvenanceBadge />
                    <img src={safeUrl} alt="AI-generated image" />
                    <MediaWatermark />
                </span>
            )
        }
    } else if (safeUrl) {
        internalComponent = (
            <span
                data-provenance="ai-generated"
                data-synthetic="true"
                aria-label="AI-generated link"
            >
                <AIProvenanceBadge />
                <a href={safeUrl}>Link</a>
            </span>
        )
    }

    return (
        <p
            className="text-sm text-gray-200 pb-2"
            data-provenance="ai-generated"
            data-synthetic="true"
        >
            {internalComponent}
        </p>
    );
}

/*
 * Take a completion, which may be a string, JSON encoded as a string, or JSON object,
 * and produce a list of ChatBlock objects. This is intended to be a one-size-fits-all
 * method for funneling different LLM output into structure that supports different media
 * types and can easily grow to support more metadata (such as speaker).
 */
const DYNAMIC_CODE_PATTERN = /\beval\s*\(|\bexec\s*\(|\bFunction\s*\(|\bnew\s+Function\b|\bsetTimeout\s*\(|\bsetInterval\s*\(|\bimport\s*\(|\brequire\s*\(|\bdocument\.write\s*\(|\bInnerHTML\b|\binnerHTML\b/i;

function sanitizeBlock(block: any): { text?: string; mimeType?: string; url?: string } | null {
    if (typeof block !== 'object' || block === null || Array.isArray(block)) {
        return null;
    }
    // Only allow known safe props
    const { text, mimeType, url } = block;
    const sanitized: { text?: string; mimeType?: string; url?: string } = {};

    if (text !== undefined) {
        if (typeof text !== 'string') return null;
        if (DYNAMIC_CODE_PATTERN.test(text)) {
            console.warn('Blocked dangerous content in LLM output (text field)');
            return null;
        }
        sanitized.text = text;
    }
    if (mimeType !== undefined) {
        if (typeof mimeType !== 'string') return null;
        if (DYNAMIC_CODE_PATTERN.test(mimeType)) {
            console.warn('Blocked dangerous content in LLM output (mimeType field)');
            return null;
        }
        // Only allow known safe MIME type prefixes
        if (!mimeType.startsWith('audio') && !mimeType.startsWith('video') && !mimeType.startsWith('image')) {
            console.warn('Blocked unknown mimeType in LLM output:', mimeType);
            return null;
        }
        sanitized.mimeType = mimeType;
    }
    if (url !== undefined) {
        if (typeof url !== 'string') return null;
        if (DYNAMIC_CODE_PATTERN.test(url)) {
            console.warn('Blocked dangerous content in LLM output (url field)');
            return null;
        }
        // Only allow http/https/data URLs
        if (!/^(https?:\/\/|data:)/i.test(url)) {
            console.warn('Blocked non-http(s) URL in LLM output:', url);
            return null;
        }
        sanitized.url = url;
    }
    return sanitized;
}

// ---------------------------------------------------------------------------
// Audit / decision-log helpers
// ---------------------------------------------------------------------------

/** Stable, non-cryptographic fingerprint of the raw completion value. */
function hashInput(value: unknown): string {
    const raw = typeof value === 'string' ? value : JSON.stringify(value);
    let h = 0x811c9dc5;
    for (let i = 0; i < raw.length; i++) {
        h ^= raw.charCodeAt(i);
        h = (Math.imul(h, 0x01000193) >>> 0);
    }
    return h.toString(16).padStart(8, '0');
}

/**
 * Writes an append-only audit record to sessionStorage under the key
 * `ai_decision_log`.  Each entry captures:
 *   - timestamp  : ISO-8601 wall-clock time
 *   - principal  : authenticated user identifier (falls back to 'anonymous')
 *   - modelId    : model identifier when available on the completion object
 *   - inputHash  : FNV-1a fingerprint of the raw completion payload
 *   - action     : the operation being audited
 */
function writeAuditRecord(action: string, completion: unknown): void {
    try {
        const record = {
            timestamp: new Date().toISOString(),
            principal:
                (typeof window !== 'undefined' &&
                    (window as any).__currentUser?.id) ??
                'anonymous',
            modelId:
                (completion !== null &&
                    typeof completion === 'object' &&
                    !Array.isArray(completion) &&
                    typeof (completion as any).model === 'string')
                    ? (completion as any).model
                    : 'unknown',
            inputHash: hashInput(completion),
            action,
        };

        // Append to the in-session log (survives page navigation within the tab).
        const existing = sessionStorage.getItem('ai_decision_log');
        const log: unknown[] = existing ? JSON.parse(existing) : [];
        log.push(record);
        sessionStorage.setItem('ai_decision_log', JSON.stringify(log));

        // Also emit a structured console entry so server-side log aggregators
        // (e.g. Datadog browser SDK) can capture it.
        console.info('[AI_AUDIT]', JSON.stringify(record));
    } catch (err) {
        // Never let audit failures break the rendering path.
        console.error('[AI_AUDIT] Failed to write audit record', err);
    }
}
// ---------------------------------------------------------------------------

export function responseToChatBlocks(completion: any) {
    // Emit a forensic audit record before any processing occurs.
    writeAuditRecord('responseToChatBlocks', completion);

    // First we try to parse completion as JSON in case we're dealing with an object.
    writeAuditRecord('responseToChatBlocks:input_received', completion);
    if (typeof completion == "string") {
        try {
            completion = JSON.parse(completion)
        } catch {
            // Do nothing; we'll just treat it as a string.
            console.log("Couldn't parse")
        }
    }
    let blocks = []
    if (typeof completion == "string") {
        console.log("still string")
        if (DYNAMIC_CODE_PATTERN.test(completion)) {
            console.warn('Blocked dangerous content in LLM output (plain string)');
        } else {
            blocks.push(<ChatBlock text={completion} />);
        }
    } else if (Array.isArray(completion)) {
        console.log("Is array")
        for (let block of completion) {
            console.log(block)
            const safeBlock = sanitizeBlock(block);
            if (safeBlock !== null) {
                blocks.push(<ChatBlock {...safeBlock} />);
            } else {
                writeAuditRecord('responseToChatBlocks:block_skipped', block);
                console.warn('Skipping invalid or dangerous block from LLM output', block);
            }
        }
    } else {
        const safeCompletion = sanitizeBlock(completion);
        if (safeCompletion !== null) {
            blocks.push(<ChatBlock {...safeCompletion} />);
        } else {
            writeAuditRecord('responseToChatBlocks:completion_skipped', completion);
            console.warn('Skipping invalid or dangerous completion object from LLM output', completion);
        }
    }
    console.log(blocks)
    return blocks
}

